---
name: Business-LCCN
version: 1.00
author:
  - 'Anirvan Chatterjee <anirvan@cpan.org>'
abstract: Work with Library of Congress Control Number (LCCN) codes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Moose: 0.34
  Moose::Util::TypeConstraints: 0
  Test::More: 0
  URI: 1.19
  perl: v5.6.1
configure_requires:
  Module::Build: 0.34
provides:
  Business::LCCN:
    file: lib/Business/LCCN.pm
    version: 1.00
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
